In [ ]:
import importlib_resources
import numpy as np
import pandas as pd

## Data loading

In [2]:
# Replace 'path_to_your_csv_file' with the actual path to your CSV file
filename = 'abalone.csv'

# Load the CSV file into a DataFrame
df = pd.read_csv(filename)

# Display the DataFrame
df.head()

Sex   "Length"   "Diameter"   "Height"   "Whole weight"   "Shucked weight"  \
0   M      0.455        0.365      0.095           0.5140             0.2245   
1   M      0.350        0.265      0.090           0.2255             0.0995   
2   F      0.530        0.420      0.135           0.6770             0.2565   
3   M      0.440        0.365      0.125           0.5160             0.2155   
4   I      0.330        0.255      0.080           0.2050             0.0895   

    "Viscera weight"   "Shell weight"   "Rings"  
0             0.1010            0.150        15  
1             0.0485            0.070         7  
2             0.1415            0.210         9  
3             0.1140            0.155        10  
4             0.0395            0.055         7

In [3]:
#remove the "" from the column names
df.columns = df.columns.str.replace('"', '')

#remove the whitespace from the column names
df.columns = df.columns.str.strip()
print(df.columns)

Index(['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight', 'Rings'],
      dtype='object')


In [4]:
raw_data = df.values

cols = range(1, 9)
X = raw_data[:, cols]

print(X)

[[0.455 0.365 0.095 ... 0.101 0.15 15]
 [0.35 0.265 0.09 ... 0.0485 0.07 7]
 [0.53 0.42 0.135 ... 0.1415 0.21 9]
 ...
 [0.6 0.475 0.205 ... 0.2875 0.308 9]
 [0.625 0.485 0.15 ... 0.261 0.296 10]
 [0.71 0.555 0.195 ... 0.3765 0.495 12]]


In [5]:
attributeNames = np.asarray(df.columns[cols])

print(attributeNames)

['Length' 'Diameter' 'Height' 'Whole weight' 'Shucked weight'
 'Viscera weight' 'Shell weight' 'Rings']


In [6]:
classLabels = raw_data[:, 0]

classNames = np.unique(classLabels)

classDict = dict(zip(classNames, range(len(classNames))))

print(classDict)

{'F': 0, 'I': 1, 'M': 2}


In [7]:
y = np.array([classDict[cl] for cl in classLabels])
print(y)

[2 2 0 ... 2 0 2]


In [8]:
N, M = X.shape
C = len(classNames)

N, M, C

(4177, 8, 3)